### ISSUE TITLE
Android templates should only be available if android.jar is in the classpath

### ISSUE THREAD

**Issue by vogella** [vogellacompany/com.vogella.saneclipse#30]
@SimonScholz can you also implement your solution from the JFace approach for the Android templates?

**Comment by SimonScholz** [comment]
First of all I created a new bug for this, because I hate redundant code: https://bugs.eclipse.org/bugs/show_bug.cgi?id=457165

**Comment by vogella** [comment]
I think the Andriod templates can be removed, Android dev went to Android Studio.
