### ISSUE TITLE
Luna - startup error.

### ISSUE THREAD

**Issue by PrabakaranSK** [vogellacompany/com.vogella.saneclipse#32]
Hi,

In Eclipse Luna, when a workspace is started, I could see the following error in "Error Log" view.

*Message:*
`Unable to retrieve the bundle from the URI: bundleclass://com.vogella.saneclipse.preferences/com.vogella.saneclipse.preferences.internal.PreferenceInitializerAddon`

*Exception Stack Trace:*
`An exception stack trace is not available.`

*Session Data:*

`eclipse.buildId=4.4.1.M20140925-0400
java.version=1.7.0
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US`

**Comment by vogella** [comment]
Thanks for the report. @SimonScholz can you test saneclipse with Eclipse 4.4.2?

**Comment by vogella** [comment]
We currently only supported latest and greatest Eclipse
