### ISSUE TITLE
requires 'bundle org.eclipse.e4.core.services 2.0.0' but it could not be found

### ISSUE THREAD

**Issue by AhmedSalem** [vogellacompany/com.vogella.saneclipse#41]
Can't install on Eclipse Juno

Version: Juno Service Release 2
Build id: 20130225-0426

**Comment by SimonScholz** [comment]
Is there any specific reason why you haven't switched to Eclipse Mars 4.5.1, yet?

**Comment by vogella** [comment]
Only Mars is supported
